image: node:lts-alpine

stages:
    - install
    - build
    - publish

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

variables:
    NPM_TOKEN: $NPM_TOKEN

before_script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

install:
    stage: install
    script:
        - npm ci
    artifacts:
        paths:
            - node_modules/

build:
    stage: build
    dependencies:
        - install
    script:
        - npm run compile
    artifacts:
        paths:
            - lib/

publish:
    stage: publish
    only:
        - main
    needs:
        - job: build
          artifacts: true
    dependencies:
        - build
    script:
        - npm publish --access public
